common_packages:
  - git
  - stow
  - fastfetch
  - openssh-clients
  - ffmpeg
  - emacs
  - wireshark
  - neovim
  - kitty
  - akmod-VirtualBox
  - VirtualBox
  - kernel-devel
  - kernel-headers
  - dkms
  - fira-code-fonts
  - sxhkd
  - dconf-editor
  - unzip
  - bzip2
  - tar