common_repos:
  - name: dotfiles
    repo: "{{ target_repo }}/dotfiles.git"
    dest: "{{ target_home }}/dotfiles"
    version: main
    type: ssh
  - name: FastCat
    repo: https://github.com/m3tozz/FastCat.git
    dest: "{{ target_home }}/FastCat"
    version: main
  - name: flower
    repo: "{{ target_repo }}/flower.git"
    dest: "{{ target_home }}/flower"
    version: main
    type: ssh
  - name: manimations
    repo: "{{ target_repo }}/manimations.git"
    dest: "{{ target_home }}/manimations"
    version: main
    type: ssh
  - name: cheetsheets
    repo: "{{ target_repo }}/cheetsheets.git"
    dest: "{{ target_home }}/cheetsheets"
    version: main
    type: ssh
    