- name: Bootstrap my machine
  hosts: myserver
  become: true

  vars_files:
    - ../vars/globals.yaml
    - ../vars/packages.yaml
    - ../vars/repos.yaml

  roles:
    - packages
    - repos
    - dotfiles